version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 30
    allow:
      - dependency-type: all

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 30

  - package-ecosystem: pip
    directory: /docs
    schedule:
      interval: daily
    open-pull-requests-limit: 30
