name: CI

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        php-version: [8.2, 8.3]
        check: [ "test", "psal -- --output-format=github", "phpstan", "style" ]

    steps:
      - uses: actions/checkout@v3.3.0
      - uses: shivammathur/setup-php@2.24.0
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
      - uses: ramsey/composer-install@v2.2.0

      - run: ${{ matrix.check }}