name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        php-version: [ 8.2 ]
        check: [ "test", "test-mutations", "psalm", "phpstan", "style" ]

    name: "PHP ${{ matrix.php-version }} → ${{ matrix.check }}"

    steps:
      - uses: actions/checkout@v4.1.1
      - uses: shivammathur/setup-php@2.29.0
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
      - uses: ramsey/composer-install@2.2.0
      - uses: mheap/phpunit-matcher-action@v1.3.0

      - run: composer ${{ matrix.check }}
